import { Composer } from "grammy";
import type { Ctx } from "../bot.js";
import { registerMainMenuItem } from "../toolkit/index.js";
import { clean, menuBack, owner, showGuests } from "../wifi-shared.js";
import { status, t } from "../i18n.js";
registerMainMenuItem({ label: "مېلمانه وګورئ", data: "guests:0", order: 20 });
const composer = new Composer<Ctx>();
composer.command("listguests", (ctx) => showGuests(ctx));
composer.callbackQuery(/^guests:(\d+)$/, async (ctx) => { await ctx.answerCallbackQuery(); await showGuests(ctx, Number(ctx.match[1]), true); });
composer.callbackQuery(/^guest:([a-f0-9]{12})$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await owner(ctx))) return; const token = clean(ctx).tokens.find((x) => x.id === ctx.match[1]); if (!token) { await ctx.editMessageText(t(ctx, "unavailable"), { reply_markup: menuBack(ctx) }); return; } await ctx.editMessageText(`${token.name || t(ctx, "guest")}\n${t(ctx, "status")}: ${status(ctx, token.status)}\n${t(ctx, "created")}: ${token.createdAt.replace("T", " ").slice(0, 16)} UTC\n${t(ctx, "expires")}: ${token.expiresAt.replace("T", " ").slice(0, 16)} UTC`, { reply_markup: menuBack(ctx) }); });
export default composer;
