import { Composer } from "grammy";
import type { Ctx } from "../bot.js";
import { registerMainMenuItem } from "../toolkit/index.js";
import { clean, menuBack, owner, showGuests } from "../wifi-shared.js";
registerMainMenuItem({ label: "List guests", data: "guests:0", order: 20 });
const composer = new Composer<Ctx>();
composer.command("listguests", (ctx) => showGuests(ctx));
composer.callbackQuery(/^guests:(\d+)$/, async (ctx) => { await ctx.answerCallbackQuery(); await showGuests(ctx, Number(ctx.match[1]), true); });
composer.callbackQuery(/^guest:([a-f0-9]{12})$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await owner(ctx))) return; const token = clean(ctx).tokens.find((x) => x.id === ctx.match[1]); if (!token) { await ctx.editMessageText("That guest access no longer exists.", { reply_markup: menuBack() }); return; } await ctx.editMessageText(`${token.name || "Guest"}\nStatus: ${token.status}\nCreated: ${token.createdAt.replace("T", " ").slice(0, 16)} UTC\nExpires: ${token.expiresAt.replace("T", " ").slice(0, 16)} UTC`, { reply_markup: menuBack() }); });
export default composer;
