// @ts-ignore qrcode publishes typings only for its Node entry; this is its browser entry.
import QRCode from "qrcode/lib/browser.js";
import { Composer, InputFile } from "grammy";
import type { Ctx, DeliveryMode } from "../bot.js";
import { inlineButton, inlineKeyboard, registerMainMenuItem } from "../toolkit/index.js";
import { beginGuest, createToken, menuBack, notify, owner } from "../wifi-shared.js";
import { t } from "../i18n.js";
registerMainMenuItem({ label: "مېلمه جوړ کړئ", data: "guest:create", order: 10 });
const composer = new Composer<Ctx>();
composer.command("newguest", (ctx) => beginGuest(ctx));
composer.callbackQuery(/^guest:delivery:(qr|text|code)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await owner(ctx))) return; ctx.session.draft = { ...ctx.session.draft, delivery: ctx.match[1] as DeliveryMode }; const hours = t(ctx, "welcome") === "Share guest Wi‑Fi without passing around your password." ? [["4 hours", "guest:expiry:4"], ["12 hours", "guest:expiry:12"], ["24 hours", "guest:expiry:24"], ["7 days", "guest:expiry:168"]] : [["۴ ساعته", "guest:expiry:4"], ["۱۲ ساعته", "guest:expiry:12"], ["۲۴ ساعته", "guest:expiry:24"], ["۷ ورځې", "guest:expiry:168"]]; await ctx.editMessageText(t(ctx, "chooseExpiry"), { reply_markup: inlineKeyboard([[inlineButton(hours[0][0], hours[0][1]), inlineButton(hours[1][0], hours[1][1])], [inlineButton(hours[2][0], hours[2][1]), inlineButton(hours[3][0], hours[3][1])], [inlineButton(t(ctx, "customHours"), "guest:expiry:custom")]]) }); });
composer.callbackQuery(/^guest:expiry:(\d+|custom)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await owner(ctx))) return; if (ctx.match[1] === "custom") { ctx.session.flow = "guest_expiry"; await ctx.editMessageText(t(ctx, "hoursPrompt")); return; } await deliver(ctx, Number(ctx.match[1])); });
async function deliver(ctx: Ctx, hours: number) { if (!Number.isInteger(hours) || hours < 1 || hours > 168 || !ctx.session.draft?.delivery) { await ctx.reply(t(ctx, "hoursInvalid")); return; } const token = await createToken(ctx, ctx.session.draft?.delivery ?? "text", hours); const details = `${t(ctx, "accessFor")} ${token.name || t(ctx, "guest")} ${t(ctx, "accessExpires")} ${token.expiresAt.replace("T", " ").slice(0, 16)} UTC.`; const keys = inlineKeyboard([[inlineButton(t(ctx, "copyPayload"), `payload:copy:${token.id}`), inlineButton(t(ctx, "revoke"), `revoke:${token.id}`)], [inlineButton(t(ctx, "viewGuests"), "guests:0")]]);
  if (token.delivery === "qr") { try { const svg = await QRCode.toString(token.payload, { type: "svg", errorCorrectionLevel: "M", margin: 2, width: 600 }); await ctx.replyWithDocument(new InputFile(new TextEncoder().encode(svg), "wifi-guest-qr.svg"), { caption: `${details}\n${t(ctx, "token")} ${token.id}`, reply_markup: keys }); } catch { await ctx.reply(`${t(ctx, "qrFailed")}\n${token.payload}`, { reply_markup: keys }); await notify(ctx, `${t(ctx, "qrFallbackNotice")}: ${token.id}.`); } }
  else if (token.delivery === "code") await ctx.reply(`${details}\n${t(ctx, "temporaryCodeLabel")} ${token.code}`, { reply_markup: keys });
  else await ctx.reply(`${details}\n${token.payload}`, { reply_markup: keys });
  await notify(ctx, `${t(ctx, "createdNotice")}: ${token.name || t(ctx, "guest")}. ${token.delivery}, ${t(ctx, "expires")} ${token.expiresAt}, ${t(ctx, "token")} ${token.id}.`);
}
composer.on("message:text", async (ctx, next) => { if (!(await owner(ctx))) return next(); const text = ctx.message.text.trim(); if (ctx.session.flow === "guest_name") { ctx.session.draft = { ...ctx.session.draft, name: text.toLowerCase() === "skip" ? undefined : text.slice(0, 80) }; ctx.session.flow = "guest_note"; await ctx.reply(t(ctx, "guestNote")); return; } if (ctx.session.flow === "guest_note") { ctx.session.draft = { ...ctx.session.draft, note: text.toLowerCase() === "skip" ? undefined : text.slice(0, 240) }; await ctx.reply(t(ctx, "chooseDelivery"), { reply_markup: inlineKeyboard([[inlineButton(t(ctx, "qrCode"), "guest:delivery:qr"), inlineButton(t(ctx, "plainText"), "guest:delivery:text")], [inlineButton(t(ctx, "temporaryCode"), "guest:delivery:code")]]) }); return; } if (ctx.session.flow === "guest_expiry") { await deliver(ctx, Number(text)); return; } return next(); });
export default composer;
