import { Composer } from "grammy";
import type { Ctx } from "../bot.js";
import { inlineButton, inlineKeyboard, registerMainMenuItem } from "../toolkit/index.js";
import { SECURITY, clean, menuBack, owner, type Security } from "../wifi-shared.js";
import { setLocale, t } from "../i18n.js";
registerMainMenuItem({ label: "امستنې", data: "settings:open", order: 40 });
const composer = new Composer<Ctx>();
async function show(ctx: Ctx, edit = false) { if (!(await owner(ctx))) return; const d = clean(ctx); const text = `${t(ctx, "defaults")}: ${d.defaultExpiryHours} ${t(ctx, "hours")}، ${d.defaultSecurity}.\n${d.profiles.length ? d.profiles.map((p) => `${t(ctx, "saved")}: ${p.ssid} (${p.security})`).join("\n") : t(ctx, "noProfiles")}`; const rows = [[inlineButton(t(ctx, "default4"), "settings:hours:4"), inlineButton(t(ctx, "default24"), "settings:hours:24")], [inlineButton(t(ctx, "chooseDefaultSecurity"), "settings:security")], [inlineButton(t(ctx, "language"), "settings:language")], [inlineButton(t(ctx, "manageWifi"), "wifi:set")], ...d.profiles.slice(0, 3).map((p) => [inlineButton(`${t(ctx, "delete")} ${p.ssid}`, `wifi:delete:${p.id}`)]), [inlineButton(t(ctx, "back"), "menu:main")]]; const kb = inlineKeyboard(rows); if (edit) await ctx.editMessageText(text, { reply_markup: kb }); else await ctx.reply(text, { reply_markup: kb }); }
composer.command("settings", (ctx) => show(ctx));
composer.callbackQuery("settings:open", async (ctx) => { await ctx.answerCallbackQuery(); await show(ctx, true); });
composer.callbackQuery(/^settings:hours:(4|24)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await owner(ctx))) return; clean(ctx).defaultExpiryHours = Number(ctx.match[1]); await show(ctx, true); });
composer.callbackQuery("settings:security", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await owner(ctx))) return; await ctx.editMessageText(t(ctx, "chooseSecurityDefault"), { reply_markup: inlineKeyboard([SECURITY.map((s) => inlineButton(s, `settings:security:${s}`)), [inlineButton(t(ctx, "back"), "settings:open")]]) }); });
composer.callbackQuery(/^settings:security:(WPA2|WPA3|WEP|Open)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await owner(ctx))) return; clean(ctx).defaultSecurity = ctx.match[1] as Security; await show(ctx, true); });
composer.callbackQuery("settings:language", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await owner(ctx))) return; const isEnglish = t(ctx, "welcome") === "Share guest Wi‑Fi without passing around your password."; await ctx.editMessageText(`${t(ctx, "language")}:`, { reply_markup: inlineKeyboard([[inlineButton(`${t(ctx, "pashto")}${isEnglish ? "" : " ✓"}`, "settings:locale:ps"), inlineButton(`${t(ctx, "english")}${isEnglish ? " ✓" : ""}`, "settings:locale:en")], [inlineButton(t(ctx, "back"), "settings:open")]]) }); });
composer.callbackQuery(/^settings:locale:(ps|en)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await owner(ctx))) return; setLocale(ctx, ctx.match[1] as "ps" | "en"); await ctx.editMessageText(t(ctx, ctx.match[1] === "ps" ? "languageSetPs" : "languageSetEn"), { reply_markup: inlineKeyboard([[inlineButton(t(ctx, "back"), "settings:open")]]) }); });
composer.callbackQuery(/^wifi:delete:([a-f0-9-]+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await owner(ctx))) return; const d = clean(ctx); const used = d.tokens.some((token) => token.profileId === ctx.match[1] && token.status === "active"); if (used) { await ctx.editMessageText(t(ctx, "profileInUse"), { reply_markup: menuBack(ctx) }); return; } d.profiles = d.profiles.filter((p) => p.id !== ctx.match[1]); await show(ctx, true); });
export default composer;
